default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: progrando

test:
  <<: *default
  database: progrando_test

production:
  <<: *default
  database: progrando_production
  username: progrando
  password: <%= ENV['PROGRANDO_DATABASE_PASSWORD'] %>
